# Generated by Django 6.0.4 on 2026-05-25 03:06

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('recipient_mail', models.EmailField(default='alrep@text.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavbarLinksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar_links', wagtail.fields.StreamField([('page_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {})}, null=True, verbose_name='Navbar Links')),
            ],
            options={
                'verbose_name': 'Navbar Links',
                'verbose_name_plural': 'Navbar Links',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressingsTypeProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('configurator_type', models.CharField(choices=[('P', 'Pressings'), ('C', 'Window Cills')], default='P', max_length=1, verbose_name='Type of configurator')),
                ('pln_to_gbp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PLN to GBP')),
                ('cost_per_weight_pln', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight Cost, PLN')),
                ('cost_per_bend_pln', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bend Cost, PLN')),
                ('cost_per_paint', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paint Cost, PLN')),
                ('static_cost_pln', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Static Cost, PLN')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProfileProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('profile_type', models.CharField(choices=[('FP', 'Flat Plate'), ('EA', 'Equal Angle'), ('UA', 'Unequal Angle'), ('US', 'U-Shape'), ('TS', 'T-Shape'), ('SQ', 'Square Tube'), ('RT', 'Rectangular Tube'), ('CT', 'Circular Tube'), ('AD', 'Ad')], default='FP', max_length=2, verbose_name='Type of image visualisation')),
                ('price_list', wagtail.fields.StreamField([('dimension', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'np. 100x200 lub Mały', 'label': 'Rozmiar', 'required': True}), 1: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'label': 'Cena za metr', 'max_digits': 10, 'min_value': 0, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('size', 0), ('price_per_meter', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProfilesTypeProductListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('pln_to_gbp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PLN to GBP')),
                ('static_cost_pln', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Static Cost, PLN')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ShoppingCartProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbp_to_pln', models.DecimalField(decimal_places=2, default=5.0, help_text='current GBP to PLN', max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=23.0, help_text='current tax in percentage (%)', max_digits=4)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=15.0, help_text='current delivery price (£)', max_digits=10)),
                ('alrep_mail', models.EmailField(default='alrep@test.com', max_length=254)),
                ('argo_mail', models.EmailField(default='argo@test.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('redirect_product_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('redirect_product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('redirect_product_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RootRedirectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
