# Generated by Django 6.0.4 on 2026-04-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rootredirectpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPage',
            new_name='PressingsTypeProductPage',
        ),
    ]
