# Generated by Django 6.0.4 on 2026-04-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_productpage_pressingstypeproductpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='configurator_type',
            field=models.CharField(choices=[('P', 'Pressings'), ('C', 'Window Cills')], default='P', max_length=1, verbose_name='Type of configurator'),
        ),
    ]
