# Generated by Django 6.0.4 on 2026-05-04 01:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_redirect_product_1_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLinksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar_links', wagtail.fields.StreamField([('page_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {})}, null=True, verbose_name='Navbar Links')),
            ],
            options={
                'verbose_name': 'Navbar Links',
                'verbose_name_plural': 'Navbar Links',
            },
            bases=('wagtailcore.page',),
        ),
    ]
