# Generated by Django 6.0.4 on 2026-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profileproductpage_configurator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileproductpage',
            name='configurator_type',
            field=models.CharField(choices=[('FP', 'Flat Plate'), ('EA', 'Equal Angle'), ('UA', 'Unequal Angle'), ('US', 'U-Shape'), ('TS', 'T-Shape'), ('SQ', 'Square Tube'), ('RT', 'Rectangular Tube'), ('CT', 'Circular Tube'), ('AD', 'Add')], default='FP', max_length=2, verbose_name='Type of image visualisation'),
        ),
    ]
