# Generated by Django 6.0.4 on 2026-05-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profileproductpage_configurator_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileproductpage',
            old_name='configurator_type',
            new_name='profile_type',
        ),
    ]
