# Generated by Django 6.0.4 on 2026-05-05 03:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_configurator_type_profileproductpage_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileproductpage',
            name='price_list',
            field=wagtail.fields.StreamField([('dimension', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'np. 100x200 lub Mały', 'label': 'Rozmiar', 'required': True}), 1: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'label': 'Cena za metr', 'max_digits': 10, 'min_value': 0, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('size', 0), ('price_per_meter', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='profileproductpage',
            name='profile_type',
            field=models.CharField(choices=[('FP', 'Flat Plate'), ('EA', 'Equal Angle'), ('UA', 'Unequal Angle'), ('US', 'U-Shape'), ('TS', 'T-Shape'), ('SQ', 'Square Tube'), ('RT', 'Rectangular Tube'), ('CT', 'Circular Tube'), ('AD', 'Ad')], default='FP', max_length=2, verbose_name='Type of image visualisation'),
        ),
    ]
