# Generated by Django 6.0.4 on 2026-05-05 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profileproductpage_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='cost_per_bend_pln',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bend Cost, PLN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='cost_per_paint',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paint Cost, PLN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='cost_per_weight_pln',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight Cost, PLN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='pln_to_gbp',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PLN to GBP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressingstypeproductpage',
            name='static_cost_pln',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Static Cost, PLN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestypeproductlistingpage',
            name='pln_to_gbp',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PLN to GBP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestypeproductlistingpage',
            name='static_cost_pln',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Static Cost, PLN'),
            preserve_default=False,
        ),
    ]
