# Generated by Django 6.0.4 on 2026-05-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='recipient_mail',
            field=models.EmailField(default='kajetan.nowakowski.2001@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
