# Generated by Django 6.0.4 on 2026-05-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contactpage_recipient_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='recipient_mail',
        ),
    ]
