# Generated by Django 6.0.4 on 2026-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_contactpage_recipient_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbp_to_pln', models.DecimalField(decimal_places=2, default=5.0, help_text='current GBP to PLN', max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=23.0, help_text='current tax in percentage (%)', max_digits=4)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=15.0, help_text='current delivery price (£)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Shop Settings',
            },
        ),
    ]
