# Generated by Django 6.0.4 on 2026-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_shopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='recipient_mail',
            field=models.EmailField(default='alrep@text.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='alrep_mail',
            field=models.EmailField(default='alrep@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='argo_mail',
            field=models.EmailField(default='argo@test.com', max_length=254),
        ),
    ]
